### PR TITLE
Fix custom range action function to now blow up

### PR DESCRIPTION
**Pull request by ChrisKraljevicD2L**
Tests will likely fail, I'll update those tomorrow

### CODE REVIEW

**Comment by ChrisKraljevicD2L** [comment]
Looks like tests are passing, ready for review/test I guess?

**Comment by CodeBaboon** [comment]
Code looks good. I can test this. Is there a defect or otherwise a description of what I'm looking to test?

**Comment by ChrisKraljevicD2L** [comment]
[This guy right here](https://rally1.rallydev.com/#/157196228032/detail/defect/174446065692)

**Comment by CodeBaboon** [comment]
Code Review Checklist
- [x] Verify that unit tests and spec tests have been written, if appropriate
- [x] Verify that CI checks are passing
- [x] n/a ~Verify that the code is behind a feature flag~
- [x] Verify that appropriate documentation has been done (readme, inline, docs.dev, etc.) and makes sense
- [x] Verify to the best of your ability that no security/privacy flaws are present
- [x] Verify that accessibility standards are held to
- [x] Verify that no lang terms are hard coded
- [x] Verify that lang terms have been submitted for translation
- [x] Other review for coding style, functionality, and best practices

Testing Checklist
Sanity Checks
- [x] Verify that unit tests and spec tests have been written, if appropriate
- [x] Verify that unit tests, spec tests, and linting are all passing
- [x] Verify that no code review comments are outstanding
- [x] Verify that the code is behind a feature flag

Acceptance/Functionality
- [x] Check that the acceptance criteria of the story has been fulfilled
- [x] Check that related functionality has not been severely affected (smoke test)
- [x] (UI) Check that the functionality is the same across browsers and devices

Accessibility (UI)
- [x] Verify that workflows can be completed via screen reader/keyboard
- [x] Verify that workflows can be completed when the browser is zoomed to 200%
- [x] Verify that there are no obvious colour contrast/combination problems

Internationalization (UI)
- [x] Verify that lang terms are not hard coded
- [x] Verify that workflows can be completed when RTL

**Pull request merged**
