### PR TITLE
US89316 - assessments status badge design update

### PR DESCRIPTION
**Pull request by colinstrancd2l**
[Story](https://rally1.rallydev.com/#/89963236876d/detail/userstory/140528603880)

### CODE REVIEW

**Comment by colinstrancd2l** [comment]
A quick note, I'm not really sure how `isOverdue`, `isDueToday` and `isCompleted` work but it seems to me that more than one of these badges can appear at a time. If that is the case, should I be reversing the order since it is left-aligned now as opposed to right-aligned?

**Comment by CodeBaboon** [comment]
1) The badges can't appear together on the same item because the service should never return a completed item as overdue, and then because of https://github.com/Brightspace/d2l-upcoming-assessments-ui/blob/master/behaviors/d2l-upcoming-assessments-behavior.html#L100
2) `min-width` is necessary for the case of different badges appearing above/below each other. So on your current page of items you might see an Overdue item and also a Complete on below it. Or maybe a Due Today and also a Complete later. Etc. It would look a bit funny if they are different widths.

**Comment by colinstrancd2l** [comment]
Got news straight from the source that we do not need `min-width` anymore. Just pushed a new commit because that source did mention there was too much room between the assignment title and the meta info

**Comment by CodeBaboon** [comment]
Testing Checklist
Sanity Checks
- [x] ~Verify that unit tests and spec tests have been written, if appropriate~ n/a
- [x] Verify that unit tests, spec tests, and linting are all passing
- [x] Verify that no code review comments are outstanding
- [x] ~Verify that the code is behind a feature flag~ n/a

Acceptance/Functionality
- [x] Check that the acceptance criteria of the story has been fulfilled
- [x] Check that related functionality has not been severely affected (smoke test)
- [x] (UI) Check that the functionality is the same across browsers and devices

Accessibility (UI)
- [x] Verify that workflows can be completed via screen reader/keyboard
- [x] Verify that workflows can be completed when the browser is zoomed to 200%
- [ ] Verify that there are no obvious colour contrast/combination problems
       ISSUE: Complete badge should be `$d2l-color-olivine-minus-1: #327846 !default;`

Internationalization (UI)
- [x] Verify that lang terms are not hard coded
- [x] Verify that workflows can be completed when RTL

**Pull request merged**
