### PR TITLE
DE27543 Add placeholders for all langterms

### PR DESCRIPTION
**Pull request by ryantmer**
Without these, nothing is rendered when these are required. With these, we at least get the english text.

### CODE REVIEW

**Comment by Surekh** [comment]
@CodeBaboon - Usually @trevorjonesd2l sends a snapshot of all terms and receives a snapshot. This change should not affect anything. UI is actual usable now even if not translated.

**Comment by CodeBaboon** [comment]
How do they use the snapshot to determine what to translate? I like that we are making the UI usable without translations but I just want to ensure we aren't causing problems downstream.

**Comment by ryantmer** [comment]
I don't think we are; I think in general we should be adding an English placeholder whenever we add a new langterm (rather than just adding the English term as we had previously been doing).

**Comment by CodeBaboon** [comment]
Sounds good to me then!

**Comment by Surekh** [comment]
@CodeBaboon - I am not sure what tool localization team uses. But the recommendation is to send snapshot and not diff.

**Pull request merged**
